kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80 # If you face any issue with port 80, you can change the hostPort to any other port like 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP