apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-awesome-app-manifest
  labels:
    app.kubernetes.io/name: my-awesome-app
    app.kubernetes.io/managed-by: manifest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-awesome-app-manifest
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50